# Generated by Django 4.2.30 on 2026-07-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
