# Generated by Django 4.2.30 on 2026-07-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, '1 день/дня/дней'), (2, '2 день/дня/дней'), (3, '3 день/дня/дней'), (4, '4 день/дня/дней'), (5, '5 день/дня/дней'), (6, '6 день/дня/дней'), (7, '7 день/дня/дней')], default=1, verbose_name='Периодичность (дней)')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveSmallIntegerField(default=60, verbose_name='Время на выполнение (секунд)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
